UgniusR/projects/__init__.py
from UgniusR.projects.views import projects_bp

UgniusR/projects/views.py
from flask import render_template, Blueprint
from UgniusR.api import public as api
import json

projects_bp = Blueprint('projects', __name__, url_prefix='/projects', template_folder='templates',
                        static_folder='static')


@projects_bp.route('/')
def projects():
    r = api.projects()
    if r.status_code == 200:
        projects = json.loads(r.data)
        return render_template('projects.html', heading='Projects', projects=projects)
    else:
        return render_template('coursework.html'), 404


@projects_bp.route('/this')
def flask_ugniusr():
    return render_template('flask_ugniusr.html', heading='Ugnius R. (Flask)')

UgniusR/projects/templates/flask_ugniusr.html
<!doctype html>
<html lang="en">
{% include 'fragments/head.html' %}

<body>
    <div class="container">
        {% include 'fragments/header_nav.html' %}
    </div>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12 blog-main">
                <h3 class="pb-3 mb-4 font-italic border-bottom">
                    {{ heading }}
                </h3>

                <h2>Purpose</h2>
                <p>
                The purpose of the site is to have an open-ended platform to experiment and showcase/document new projects. The full
                source code can be found through the link on the bottom of this page.
                </p>

                <h2>Technology</h2>
                <p>
                The site is built using the Flask Framework and deployed on Ubuntu using uWSGI and Nginx.
                </p>

                <h3>Javascript Framework?</h3>
                <p>
                While I acknowledge the existence and importance of the modern Javascript options (Angular/Node.js), my priority has
                never been front-end development. For the purpose of this project, the current technology is sufficient and allows
                me to become familiar with the fundamentals.

                <p>
                I find it is the best use of my time to expand my knowledge of my current interests. If someday my interests shift to Javascript
                frameworks and front-end development, this website would very likely be the target of experimentation.
                </p>

                <h3>CSS</h3>
                <p>
                The site uses the Bootstrap library and is based on an example page provided by Bootstrap.
                </p>

                <h2>Structure</h2>
                <p>
                This project is structured to allow for future expansion by using modular components called Blueprints.
                There are currently three primary Blueprints: 'main', 'projects', and 'api'.
                </p>

                <h2>API</h2>
                <p>
                The API provides some resources that are used throughout the program. The API can be access through
                '/api/public'. In the future, I intend to expand this API to include authentication features. The
                resources the API provides are not very useful outside of the context of this site, but developing it
                provides some exposure to REST concepts.
                </p>

        </div><!-- /.blog-main -->

      </div><!-- /.row -->

    </main><!-- /.container -->

    {% include 'fragments/footer.html' %}

</body>
</html>

UgniusR/projects/templates/projects.html
<!doctype html>
<html lang="en">
{% include 'fragments/head.html' %}

<body>
    <div class="container">
        {% include 'fragments/header_nav.html' %}
    </div>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12 blog-main">
                <h3 class="pb-3 mb-4 font-italic border-bottom">
                    {{ heading }}
                </h3>

                    <div class="row mb-2">
                        <div class="col-md-6">
                            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                                <div class="card-body d-flex flex-column align-items-start">
                                    <strong class="d-inline-block mb-2 text-primary">Projects</strong>
                                    <h3 class="mb-0">
                                        <a class="text-dark" href="{{ url_for('projects.flask_ugniusr') }}">Ugnius R.</a>
                                    </h3>
                                    <div class="mb-1 text-muted">Python/Flask</div>
                                    <p class="card-text mb-auto">You are currently using it!</p>
                                    <a href="{{ url_for('projects.flask_ugniusr') }}">Read more...</a>
                                </div>
                                <img class="card-img-right flex-auto d-none d-md-block" src="{{ url_for('projects.static', filename='images/flask.png') }}" >
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                                <div class="card-body d-flex flex-column align-items-start">
                                    <strong class="d-inline-block mb-2 text-primary">Projects</strong>
                                    <h3 class="mb-0">
                                        <a class="text-dark" href="#">16x16 LED Display</a>
                                    </h3>
                                    <div class="mb-1 text-muted">C++</div>
                                    <p class="card-text mb-auto">
                                        Built from scratch and powered by C++ on a Raspberry Pi.
                                    </p>
                                    <a href="#"></a>
                                </div>
                                <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?text=Coming soon" alt="Card image cap">
                            </div>
                        </div>

                    </div>

        </div><!-- /.blog-main -->

      </div><!-- /.row -->

    </main><!-- /.container -->

    {% include 'fragments/footer.html' %}

  </body>
</html>